import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { Db, isUniqueViolation } from '../src/db/database.js';
import { migrate } from '../src/db/migrations.js';

describe('Db (PGlite)', () => {
  let db: Db;
  beforeEach(async () => {
    db = await Db.open('memory:');
    await db.exec(
      'CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v TEXT, n NUMERIC(78,0), b BIGINT)',
    );
  });
  afterEach(async () => {
    await db.close();
  });

  it('translates positional and named placeholders, including repeated names', async () => {
    const id = await db.insert('INSERT INTO t (v, n, b) VALUES (?, ?, ?)', [
      'a',
      '123456789012345678901234567890',
      1_700_000_000_000,
    ]);
    expect(id).toBe(1);
    const row = await db.get<{ v: string; n: string; b: number }>(
      'SELECT v, n, b FROM t WHERE id = :id AND v = :v OR (:v = v AND id = :id)',
      { id, v: 'a' },
    );
    expect(row).toEqual({ v: 'a', n: '123456789012345678901234567890', b: 1_700_000_000_000 });
  });

  it('leaves literals, casts and quoted identifiers alone', async () => {
    await db.run('INSERT INTO t (v) VALUES (?)', ['x']);
    const row = await db.get<{ q: string; c: string; k: string }>(
      `SELECT 'is it ? or :name' AS q, v::text AS c, '1'::int::text AS "k" FROM t`,
    );
    expect(row).toEqual({ q: 'is it ? or :name', c: 'x', k: '1' });
  });

  it('rejects a missing named parameter instead of binding null silently', async () => {
    await expect(db.get('SELECT :a AS a', {})).rejects.toThrow(/missing SQL parameter :a/);
  });

  it('rolls back a failed transaction and keeps a nested savepoint failure local', async () => {
    await expect(
      db.tx(async () => {
        await db.run("INSERT INTO t (v) VALUES ('rolled back')");
        throw new Error('boom');
      }),
    ).rejects.toThrow('boom');
    await db.tx(async () => {
      await db.run("INSERT INTO t (v) VALUES ('outer')");
      await expect(
        db.tx(async () => {
          await db.run("INSERT INTO t (v) VALUES ('inner')");
          throw new Error('inner failure');
        }),
      ).rejects.toThrow('inner failure');
    });
    expect((await db.all<{ v: string }>('SELECT v FROM t ORDER BY id')).map((r) => r.v)).toEqual(['outer']);
  });

  it('never lets an unrelated concurrent query run inside an open transaction', async () => {
    let release!: () => void;
    const gate = new Promise<void>((r) => (release = r));
    const txDone = db
      .tx(async () => {
        await db.run("INSERT INTO t (v) VALUES ('in tx')");
        await gate;
        throw new Error('abort');
      })
      .catch(() => undefined);
    const outside = db.run("INSERT INTO t (v) VALUES ('outside')");
    release();
    await Promise.all([txDone, outside]);
    expect((await db.all<{ v: string }>('SELECT v FROM t')).map((r) => r.v)).toEqual(['outside']);
  });

  it('reports unique violations with the Postgres error code', async () => {
    await db.exec('CREATE TABLE u (k TEXT UNIQUE)');
    await db.run("INSERT INTO u VALUES ('a')");
    const err = await db.run("INSERT INTO u VALUES ('a')").catch((e: unknown) => e);
    expect(isUniqueViolation(err)).toBe(true);
  });
});

describe('migrations (PGlite)', () => {
  it('apply once, are idempotent, and enforce the append-only and immutability triggers', async () => {
    const db = await Db.open('memory:');
    expect(await migrate(db)).toEqual([1]);
    expect(await migrate(db)).toEqual([]);
    await db.run(
      "INSERT INTO audit_events (ts, component, severity, type, message) VALUES (1, 'c', 'INFO', 't', 'm')",
    );
    await expect(db.run('DELETE FROM audit_events')).rejects.toThrow(/audit_events is append-only/);
    await expect(db.run("UPDATE audit_events SET message = 'x'")).rejects.toThrow(/append-only/);
    expect((await db.get<{ status: string }>('SELECT status FROM bot_state WHERE id = 1'))!.status).toBe(
      'STOPPED',
    );
    await db.close();
  });
});
