/**
 * PostgreSQL schema migrations (embedded so the bundled server needs no loose files). The same migrations run
 * against embedded PGlite (local default and tests), a local Postgres container and Supabase. Append new
 * migrations; never edit an applied one.
 *
 * Conventions: money = NUMERIC(78,0) wei (exceeds int64; returned as exact decimal strings), prices = BIGINT with
 * 8 decimals, chain times = BIGINT unix seconds, application event times = BIGINT unix milliseconds, flags =
 * SMALLINT 0/1, JSON payloads = TEXT, application timestamps = ISO-8601 TEXT.
 */
import type { Db } from './database.js';

const NOW = `(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))`;
const ID = 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
const FLAG = (name: string, dflt: 0 | 1) =>
  `${name} SMALLINT NOT NULL DEFAULT ${dflt} CHECK (${name} IN (0,1))`;

export const MIGRATIONS: readonly { id: number; name: string; sql: string }[] = [
  {
    id: 1,
    name: 'initial schema',
    sql: `
CREATE TABLE markets (
  id ${ID},
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  symbol TEXT NOT NULL,
  underlying_asset TEXT NOT NULL,
  quote_asset TEXT NOT NULL,
  chain TEXT NOT NULL,
  chain_id INTEGER NOT NULL,
  contract_address TEXT NOT NULL,
  protocol TEXT NOT NULL CHECK (protocol IN ('PANCAKESWAP_V2','PANCAKESWAP_V1','PRDT')),
  timing TEXT NOT NULL CHECK (timing IN ('TIMESTAMP','BLOCK')),
  ${FLAG('tradable', 0)},
  ${FLAG('active', 1)},
  interval_seconds INTEGER,
  buffer_seconds INTEGER,
  treasury_fee_bps INTEGER NOT NULL DEFAULT 300,
  min_bet_wei NUMERIC(78,0),
  oracle_address TEXT,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  updated_at TEXT NOT NULL DEFAULT ${NOW},
  UNIQUE (chain_id, contract_address)
);

CREATE TABLE rounds (
  id ${ID},
  market_id BIGINT NOT NULL REFERENCES markets(id),
  epoch BIGINT NOT NULL,
  start_time BIGINT,
  lock_time BIGINT,
  close_time BIGINT,
  start_block BIGINT,
  lock_block BIGINT,
  close_block BIGINT,
  lock_price BIGINT,
  close_price BIGINT,
  lock_oracle_id TEXT,
  close_oracle_id TEXT,
  total_amount NUMERIC(78,0) NOT NULL DEFAULT 0,
  bull_amount NUMERIC(78,0) NOT NULL DEFAULT 0,
  bear_amount NUMERIC(78,0) NOT NULL DEFAULT 0,
  reward_base_cal_amount NUMERIC(78,0) NOT NULL DEFAULT 0,
  reward_amount NUMERIC(78,0) NOT NULL DEFAULT 0,
  ${FLAG('oracle_called', 0)},
  bull_payout DOUBLE PRECISION,
  bear_payout DOUBLE PRECISION,
  status TEXT NOT NULL CHECK (status IN ('UPCOMING','OPEN','LOCKING','LIVE','CLOSING','ENDED','CANCELLED')),
  outcome TEXT CHECK (outcome IN ('BULL','BEAR','TIE','CANCELLED')),
  ${FLAG('is_final', 0)},
  source TEXT NOT NULL CHECK (source IN ('CHAIN','CSV_IMPORT')),
  observed_block BIGINT,
  observed_at BIGINT,
  extra TEXT,
  finalized_at TEXT,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  updated_at TEXT NOT NULL DEFAULT ${NOW},
  UNIQUE (market_id, epoch),
  CHECK (is_final = 0 OR outcome IS NOT NULL)
);
CREATE INDEX idx_rounds_market_close ON rounds(market_id, close_time);
CREATE INDEX idx_rounds_market_final ON rounds(market_id, is_final, epoch);
CREATE INDEX idx_rounds_outcome ON rounds(market_id, outcome);

-- Final round data can only be replaced by an authoritative chain observation of a CSV-imported row,
-- and every such correction is preserved in round_corrections.
CREATE FUNCTION rounds_final_immutable() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF OLD.is_final = 1 AND NOT (OLD.source = 'CSV_IMPORT' AND NEW.source = 'CHAIN') AND (
    NEW.is_final IS DISTINCT FROM OLD.is_final OR NEW.outcome IS DISTINCT FROM OLD.outcome OR
    NEW.lock_price IS DISTINCT FROM OLD.lock_price OR NEW.close_price IS DISTINCT FROM OLD.close_price OR
    NEW.bull_amount IS DISTINCT FROM OLD.bull_amount OR NEW.bear_amount IS DISTINCT FROM OLD.bear_amount OR
    NEW.reward_amount IS DISTINCT FROM OLD.reward_amount OR
    NEW.reward_base_cal_amount IS DISTINCT FROM OLD.reward_base_cal_amount) THEN
    RAISE EXCEPTION 'final round data is immutable';
  END IF;
  RETURN NEW;
END
$fn$;
CREATE TRIGGER rounds_final_immutable BEFORE UPDATE ON rounds
  FOR EACH ROW EXECUTE FUNCTION rounds_final_immutable();

CREATE TABLE round_corrections (
  id ${ID},
  round_id BIGINT NOT NULL REFERENCES rounds(id),
  previous TEXT NOT NULL,
  corrected TEXT NOT NULL,
  source TEXT NOT NULL,
  detected_at TEXT NOT NULL DEFAULT ${NOW}
);

CREATE VIEW rounds_v AS
SELECT r.*,
  CASE WHEN p.lock_time IS NOT NULL AND r.start_time IS NOT NULL AND abs(r.start_time - p.lock_time) <= 60
       THEN p.lock_price END AS start_price
FROM rounds r
LEFT JOIN rounds p ON p.market_id = r.market_id AND p.epoch = r.epoch - 1;

CREATE TABLE sync_state (
  market_id BIGINT PRIMARY KEY REFERENCES markets(id),
  last_synced_epoch BIGINT,
  last_sync_at TEXT,
  last_reconcile_at TEXT,
  reconcile_cursor BIGINT
);

CREATE TABLE import_runs (
  id ${ID},
  market_id BIGINT NOT NULL REFERENCES markets(id),
  source TEXT NOT NULL,
  started_at TEXT NOT NULL DEFAULT ${NOW},
  finished_at TEXT,
  rows_read INTEGER NOT NULL DEFAULT 0,
  inserted INTEGER NOT NULL DEFAULT 0,
  unchanged INTEGER NOT NULL DEFAULT 0,
  duplicates_identical INTEGER NOT NULL DEFAULT 0,
  duplicates_conflicting INTEGER NOT NULL DEFAULT 0,
  malformed INTEGER NOT NULL DEFAULT 0,
  conflicts_with_db INTEGER NOT NULL DEFAULT 0,
  report TEXT
);

CREATE TABLE wallets (
  id ${ID},
  address TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('SIGNER','WATCH')),
  ${FLAG('enabled', 1)},
  user_rounds_cursor BIGINT NOT NULL DEFAULT 0,
  last_synced_at TEXT,
  created_at TEXT NOT NULL DEFAULT ${NOW}
);

CREATE TABLE strategies (
  id ${ID},
  slug TEXT NOT NULL UNIQUE,
  plugin TEXT NOT NULL,
  name TEXT NOT NULL,
  version TEXT NOT NULL,
  description TEXT NOT NULL,
  market_id BIGINT NOT NULL REFERENCES markets(id),
  config TEXT NOT NULL,
  ${FLAG('enabled', 0)},
  ${FLAG('paper_trading_enabled', 1)},
  ${FLAG('live_trading_enabled', 0)},
  created_at TEXT NOT NULL DEFAULT ${NOW},
  updated_at TEXT NOT NULL DEFAULT ${NOW}
);

CREATE TABLE claims (
  id ${ID},
  wallet_id BIGINT NOT NULL REFERENCES wallets(id),
  market_id BIGINT NOT NULL REFERENCES markets(id),
  epochs TEXT NOT NULL,
  tx_hash TEXT UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('PENDING','SUBMITTED','CONFIRMED','FAILED')),
  gas_cost NUMERIC(78,0),
  error TEXT,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  updated_at TEXT NOT NULL DEFAULT ${NOW}
);

CREATE TABLE trades (
  id ${ID},
  uid TEXT NOT NULL UNIQUE,
  mode TEXT NOT NULL CHECK (mode IN ('PAPER','LIVE')),
  source TEXT NOT NULL CHECK (source IN ('BOT','MANUAL','IMPORTED')),
  wallet_id BIGINT REFERENCES wallets(id),
  market_id BIGINT NOT NULL REFERENCES markets(id),
  round_id BIGINT NOT NULL REFERENCES rounds(id),
  epoch BIGINT NOT NULL,
  strategy_id BIGINT REFERENCES strategies(id),
  decision_id BIGINT,
  direction TEXT NOT NULL CHECK (direction IN ('BULL','BEAR')),
  amount NUMERIC(78,0) NOT NULL,
  entry_bull_payout DOUBLE PRECISION,
  entry_bear_payout DOUBLE PRECISION,
  placed_at BIGINT NOT NULL,
  tx_hash TEXT UNIQUE,
  nonce BIGINT,
  block_number BIGINT,
  gas_used NUMERIC(78,0),
  gas_price NUMERIC(78,0),
  gas_cost NUMERIC(78,0),
  status TEXT NOT NULL CHECK (status IN ('PENDING','SUBMITTING','SUBMITTED','CONFIRMED','SETTLED','FAILED')),
  result TEXT CHECK (result IN ('WON','LOST','REFUNDED')),
  payout NUMERIC(78,0),
  gross_pnl NUMERIC(78,0),
  net_pnl NUMERIC(78,0),
  claim_status TEXT NOT NULL DEFAULT 'NOT_APPLICABLE'
    CHECK (claim_status IN ('NOT_APPLICABLE','UNCLAIMED','CLAIMING','CLAIMED')),
  claim_id BIGINT REFERENCES claims(id),
  claim_gas_cost NUMERIC(78,0),
  error TEXT,
  error_class TEXT,
  settled_at BIGINT,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  updated_at TEXT NOT NULL DEFAULT ${NOW},
  CHECK (mode = 'PAPER' OR wallet_id IS NOT NULL),
  CHECK (status <> 'SETTLED' OR (result IS NOT NULL AND payout IS NOT NULL))
);
-- The contract accepts one bet per address per round; mirror that for live trades.
CREATE UNIQUE INDEX uniq_live_bet_per_round ON trades(wallet_id, market_id, epoch)
  WHERE mode = 'LIVE' AND status <> 'FAILED';
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_mode_placed ON trades(mode, placed_at);
CREATE INDEX idx_trades_strategy ON trades(strategy_id);
CREATE INDEX idx_trades_round ON trades(round_id);

CREATE TABLE trade_events (
  id ${ID},
  trade_id BIGINT NOT NULL REFERENCES trades(id),
  from_status TEXT,
  to_status TEXT NOT NULL,
  at BIGINT NOT NULL,
  detail TEXT
);
CREATE INDEX idx_trade_events_trade ON trade_events(trade_id);

CREATE FUNCTION reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END
$fn$;
CREATE TRIGGER trade_events_append_only BEFORE UPDATE OR DELETE ON trade_events
  FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE TABLE strategy_decisions (
  id ${ID},
  strategy_id BIGINT NOT NULL REFERENCES strategies(id),
  market_id BIGINT NOT NULL REFERENCES markets(id),
  round_id BIGINT NOT NULL REFERENCES rounds(id),
  epoch BIGINT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('PAPER','LIVE')),
  signal TEXT CHECK (signal IN ('BUY_UP','BUY_DOWN','WAIT','SKIP')),
  confidence DOUBLE PRECISION,
  decision TEXT NOT NULL CHECK (decision IN ('TRADE','NO_TRADE')),
  direction TEXT CHECK (direction IN ('BULL','BEAR')),
  intended_amount NUMERIC(78,0),
  actual_amount NUMERIC(78,0),
  expected_edge DOUBLE PRECISION,
  reason TEXT NOT NULL,
  rationale TEXT,
  risk_checks TEXT NOT NULL DEFAULT '[]',
  inputs TEXT,
  indicators TEXT,
  error TEXT,
  trade_id BIGINT REFERENCES trades(id),
  decided_at BIGINT NOT NULL,
  seconds_to_lock DOUBLE PRECISION,
  UNIQUE (strategy_id, round_id, mode)
);
CREATE INDEX idx_decisions_round ON strategy_decisions(round_id);
CREATE INDEX idx_decisions_decided ON strategy_decisions(decided_at);

CREATE TABLE portfolio_snapshots (
  id ${ID},
  mode TEXT NOT NULL CHECK (mode IN ('PAPER','LIVE')),
  wallet_id BIGINT REFERENCES wallets(id),
  taken_at BIGINT NOT NULL,
  balance NUMERIC(78,0) NOT NULL,
  available NUMERIC(78,0) NOT NULL,
  deployed NUMERIC(78,0) NOT NULL,
  claimable NUMERIC(78,0) NOT NULL,
  realized_pnl NUMERIC(78,0) NOT NULL,
  drawdown NUMERIC(78,0) NOT NULL,
  roi DOUBLE PRECISION,
  win_rate DOUBLE PRECISION,
  loss_rate DOUBLE PRECISION,
  trades INTEGER NOT NULL
);
CREATE INDEX idx_snapshots_mode_time ON portfolio_snapshots(mode, taken_at);

CREATE TABLE bot_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  status TEXT NOT NULL CHECK (status IN ('STOPPED','RUNNING','PAUSED','EMERGENCY_STOPPED')),
  status_reason TEXT,
  ${FLAG('live_armed', 0)},
  live_armed_at TEXT,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT ${NOW}
);
INSERT INTO bot_state (id, status, status_reason) VALUES (1, 'STOPPED', 'initial state');

CREATE TABLE audit_events (
  id ${ID},
  ts BIGINT NOT NULL,
  component TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('DEBUG','INFO','WARN','ERROR','CRITICAL')),
  type TEXT NOT NULL,
  market_id BIGINT,
  epoch BIGINT,
  strategy_id BIGINT,
  trade_id BIGINT,
  tx_hash TEXT,
  message TEXT NOT NULL,
  metadata TEXT
);
CREATE INDEX idx_audit_ts ON audit_events(ts);
CREATE INDEX idx_audit_type ON audit_events(type);
CREATE INDEX idx_audit_epoch ON audit_events(epoch);
CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE TABLE backtest_runs (
  id ${ID},
  status TEXT NOT NULL CHECK (status IN ('RUNNING','DONE','FAILED')),
  request TEXT NOT NULL,
  result TEXT,
  error TEXT,
  progress DOUBLE PRECISION NOT NULL DEFAULT 0,
  duration_ms BIGINT,
  heartbeat_at BIGINT,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  finished_at TEXT
);
`,
  },
  {
    id: 2,
    name: 'round pool events',
    sql: `
-- One row per BetBull/BetBear log: the order and timing of money entering each round's pool. Research uses it to
-- reconstruct what the pool looked like at any decision time; a round's events are trusted only when they sum
-- exactly (in wei) to the round's final bull/bear amounts.
CREATE TABLE round_pool_events (
  id ${ID},
  market_id BIGINT NOT NULL REFERENCES markets(id),
  epoch BIGINT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('BULL','BEAR')),
  sender TEXT NOT NULL,
  amount NUMERIC(78,0) NOT NULL CHECK (amount > 0),
  block_number BIGINT NOT NULL,
  block_time BIGINT NOT NULL,
  tx_hash TEXT NOT NULL,
  log_index INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  UNIQUE (market_id, tx_hash, log_index)
);
CREATE INDEX idx_pool_events_round ON round_pool_events(market_id, epoch, block_time);
CREATE INDEX idx_pool_events_block ON round_pool_events(market_id, block_number);
CREATE TRIGGER round_pool_events_append_only BEFORE UPDATE OR DELETE ON round_pool_events
  FOR EACH ROW EXECUTE FUNCTION reject_mutation();

-- Collected block range [from_block, to_block] (empty while from_block > to_block). Forward collection extends
-- to_block towards the head; backfill lowers from_block until anchor_block − the configured depth, or until the
-- log node stops serving that history.
CREATE TABLE pool_event_sync (
  market_id BIGINT PRIMARY KEY REFERENCES markets(id),
  anchor_block BIGINT NOT NULL,
  from_block BIGINT NOT NULL,
  to_block BIGINT NOT NULL,
  ${FLAG('backfill_done', 0)},
  backfill_failures INTEGER NOT NULL DEFAULT 0,
  forward_failures INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  updated_at TEXT NOT NULL DEFAULT ${NOW}
);

-- Block ranges given up on after repeated failures; rounds inside them fail the completeness check.
CREATE TABLE pool_event_gaps (
  id ${ID},
  market_id BIGINT NOT NULL REFERENCES markets(id),
  from_block BIGINT NOT NULL,
  to_block BIGINT NOT NULL,
  reason TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ${NOW}
);
`,
  },
];

/** Applies pending migrations in one transaction under an advisory lock, so concurrent processes cannot race. */
export async function migrate(db: Db): Promise<number[]> {
  return db.tx(async () => {
    await db.exec('SELECT pg_advisory_xact_lock(727274)');
    await db.exec(`CREATE TABLE IF NOT EXISTS schema_migrations (
      id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL DEFAULT ${NOW})`);
    const applied = new Set(
      (await db.all<{ id: number }>('SELECT id FROM schema_migrations')).map((r) => r.id),
    );
    const ran: number[] = [];
    for (const m of MIGRATIONS) {
      if (applied.has(m.id)) continue;
      await db.exec(m.sql);
      await db.run('INSERT INTO schema_migrations (id, name) VALUES (?, ?)', [m.id, m.name]);
      ran.push(m.id);
    }
    return ran;
  });
}
